# Generated by Django 5.1.4 on 2024-12-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('size', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='photos/room')),
                ('capacity', models.CharField(max_length=30)),
                ('bed', models.CharField(max_length=100)),
                ('price_per_night', models.IntegerField()),
                ('is_avaliable', models.BooleanField(default=True)),
            ],
        ),
    ]
