# Generated by Django 5.1.6 on 2025-03-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest',
            new_name='guests',
        ),
    ]
