# Generated by Django 5.1.6 on 2025-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
